"""H4 result tables and the D13 verdict (results/H4.md sections 5-6), regenerated from results/ only.

Usage:  python -m analysis.h4_tables   (also called by analysis.plots)

Writes results/h4_results.md. Rule (D13, fixed before the data): an intervention rescues when the
ticket - shuffle advantage is >= +2.0 pp at >= 2 of the 3 masks. Manipulation checks: SAM must lower
max S(25-3k) below plain (a) at the same mask; the anchor must raise R_0.2 at step 3,000 above (a).
A verdict whose manipulation did not move its target variable is "inconclusive".
"""
from __future__ import annotations

import json

from src.metrics import stability_summary
from src.utils import RESULTS

ROUNDS = {3: "34.5%", 6: "12.0%", 8: "6.0%"}
CONDS = {"a": "h4_high", "b": "h4_high_sam", "c": "h4_high_anchor"}
RESCUE_PP, RESCUE_MASKS = 2.0, 2
R02_AT = 3000


def _load(cond: str, rnd: int, variant: str) -> dict | None:
    p = RESULTS / cond / "seed0" / f"round{rnd}_{variant}.json"
    if not p.exists():
        return None
    r = json.loads(p.read_text())
    r02_3k = next((s.get("R02") for s in r["sharpness"] if s["step"] == R02_AT), float("nan"))
    return {"acc": 100 * r["test"]["acc"], "R02": r["R02"], "R02_3k": r02_3k, **stability_summary(r["sharpness"])}


def _f(x, fmt="{:.3f}") -> str:
    return "—" if x is None or x != x else fmt.format(x)


def collect() -> dict:
    return {(k, rnd, v): _load(c, rnd, v) for k, c in CONDS.items() for rnd in ROUNDS for v in ("ticket", "shuffle")}


def advantage(d: dict, k: str, rnd: int) -> float | None:
    t, s = d[(k, rnd, "ticket")], d[(k, rnd, "shuffle")]
    return None if t is None or s is None else t["acc"] - s["acc"]


def verdict(d: dict, k: str) -> str:
    advs = [advantage(d, k, r) for r in ROUNDS]
    n_done, n_pass = sum(a is not None for a in advs), sum(a is not None and a >= RESCUE_PP for a in advs)
    if n_pass >= RESCUE_MASKS:
        rule = "rescues"
    elif n_pass + (len(ROUNDS) - n_done) < RESCUE_MASKS:
        rule = "does not rescue"
    else:
        return f"pending ({n_pass}/{n_done} masks ≥ +{RESCUE_PP} pp so far)"
    if k == "a":
        return f"warm03 masks {'still win' if rule == 'rescues' else 'fail'} at η = 0.1 ({n_pass}/{n_done} masks ≥ +{RESCUE_PP} pp)"
    # manipulation check vs (a), on the tickets at every mask where both exist
    key, want = ("max_S_train", "lower") if k == "b" else ("R02_3k", "higher")
    pairs = [(d[(k, r, "ticket")], d[("a", r, "ticket")]) for r in ROUNDS]
    pairs = [(x[key], y[key]) for x, y in pairs if x and y]
    if not pairs:
        return f"{rule} by the rule ({n_pass}/{n_done}); manipulation check pending (needs (a))"
    moved = sum((x < y) if want == "lower" else (x > y) for x, y in pairs)
    ok = moved > len(pairs) / 2
    return (f"{rule if ok else 'inconclusive'} ({n_pass}/{n_done} masks ≥ +{RESCUE_PP} pp; "
            f"{key} {want} than (a) at {moved}/{len(pairs)} masks)")


def main() -> None:
    d = collect()
    lines = ["# H4 results (generated by analysis/h4_tables.py; do not edit by hand)", "",
             "Test accuracy %, ticket / shuffle / advantage (pp).", "",
             "| Mask | (a) plain | (b) SAM | (c) anchor |", "|---|---|---|---|"]
    for rnd, lab in ROUNDS.items():
        cells = []
        for k in CONDS:
            t, s, a = d[(k, rnd, "ticket")], d[(k, rnd, "shuffle")], advantage(d, k, rnd)
            cells.append(f"{_f(t and t['acc'], '{:.2f}')} / {_f(s and s['acc'], '{:.2f}')} / {_f(a, '{:+.2f}')}")
        lines.append(f"| {lab} | " + " | ".join(cells) + " |")
    lines += ["", "Tickets: max S(25–3k) / S(0) / R_0.2 at 3k / R_0.2 final, for (a) | (b) | (c).", "",
              "| Mask | (a) plain | (b) SAM | (c) anchor |", "|---|---|---|---|"]
    for rnd, lab in ROUNDS.items():
        cells = []
        for k in CONDS:
            t = d[(k, rnd, "ticket")] or {}
            cells.append(" / ".join(_f(t.get(m)) for m in ("max_S_train", "S0", "R02_3k", "R02")))
        lines.append(f"| {lab} | " + " | ".join(cells) + " |")
    sel = RESULTS / "h4_high_anchor" / "lam_selection.json"
    if sel.exists():
        s = json.loads(sel.read_text())
        lines += ["", f"Anchor lam chosen: {s['chosen']} (R_0.2 at 3k: "
                  + ", ".join(f"lam {k} → {v:.3f}" for k, v in s["R02"].items())
                  + f"; target {s['target_R02']:.3f}; reached: {s['reached_target']})."]
    lines += ["", "## Verdicts (D13)", ""] + [f"- **({k}) {CONDS[k]}**: {verdict(d, k)}" for k in CONDS] + [""]
    (RESULTS / "h4_results.md").write_text("\n".join(lines))
    print("\n".join(lines))


if __name__ == "__main__":
    main()
