"""Summarise the Conv-4 / Fashion-MNIST pilot JSONs in `pilot_results/` (spec section 10).

Reads the three pilot run sets written by `pilot/lt_sharp.py`:
  * `res_{low,high,high_warm}.json`            original 2-epoch CPU pilot (eta = 0.01 / 0.05)
  * `res_full_{low,high_nowarm,high_warm}.json` 4-epoch CPU team re-run (eta = 0.01 / 0.1)
  * `res_gpu_{low,high_nowarm,high_warm}.json`  same 4-epoch settings, re-run on CUDA

and writes, into `pilot_results/`:
  * `pilot_summary.csv`   one row per (run set, condition, round, variant)
  * `pilot_tables.md`     per-chain ticket-vs-reinit tables with the section-5 winning-ticket verdict
  * `fig_pilot_acc.png`   test accuracy vs % weights remaining (ticket, reinit, dense line)
  * `fig_pilot_spike.png` early loss spike vs final accuracy (collapse predictor)

The stability ratio uses the learning rate actually in effect at step 100,
S = eta_100 * lambda_max(100) / (2 + 2*beta) (Kalra & Barkeshli 2024), not the peak rate.
Usage: python -m analysis.pilot_summary
"""
from __future__ import annotations

import json
import math
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
PILOT = ROOT / "pilot_results"
BETA = 0.9
CHANCE_ACC = 0.20  # section 5: a run below this did not train
SETS = {  # run set -> {condition label: file tag}
    "2ep_cpu": {"low": "low", "high": "high", "high_warm": "high_warm"},
    "4ep_cpu": {"low": "full_low", "high": "full_high_nowarm", "high_warm": "full_high_warm"},
    "4ep_gpu": {"low": "gpu_low", "high": "gpu_high_nowarm", "high_warm": "gpu_high_warm"},
}
SET_TITLE = {"2ep_cpu": "Original pilot (2 ep, CPU)", "4ep_cpu": "Team re-run (4 ep, CPU)",
             "4ep_gpu": "GPU re-run (4 ep, CUDA)"}
TICKET, REINIT, DENSE, INK, MUTED = "#2a78d6", "#eb6834", "#52514e", "#0b0b0b", "#8a8984"


def eta_at_step(args: dict, step: int = 100) -> float:
    """Learning rate used by `pilot/lt_sharp.py` for its `step`-th update (linear warmup)."""
    spe = math.ceil(args["ntrain"] / 128)
    wu = int(args["warmup"] * spe)
    return args["lr"] * min(1.0, step / wu) if wu > 0 else args["lr"]


def load_rows() -> pd.DataFrame:
    """Flatten every pilot JSON into one row per (set, condition, round, variant)."""
    out = []
    for run_set, conds in SETS.items():
        for cond, tag in conds.items():
            d = json.loads((PILOT / f"res_{tag}.json").read_text())
            a, eta = d["args"], eta_at_step(d["args"])
            for r in d["rows"]:
                for var, pre, lam0, lam100, spike in (
                        ("ticket", "ticket_", "lam0", "lam100", "spike"),
                        ("reinit", "reinit_", "lam0_reinit", "lam100_reinit", "reinit_spike")):
                    if f"{pre}acc" not in r:
                        continue
                    acc = r[f"{pre}acc"]
                    out.append(dict(
                        run_set=run_set, condition=cond, lr=a["lr"], warmup_ep=a["warmup"],
                        epochs=a["epochs"], device=a.get("device", "cpu"), round=r["round"],
                        remain_pct=100 * r["remain"], variant=var, acc=acc,
                        prec=r[f"{pre}prec"], rec=r[f"{pre}rec"], f1=r[f"{pre}f1"], auc=r[f"{pre}auc"],
                        lam0=r.get(lam0), lam100=r.get(lam100), eta100=eta,
                        S100=eta * r.get(lam100, float("nan")) / (2 + 2 * BETA),
                        spike=r.get(spike), diverged_nan=bool(r["diverged"]) if var == "ticket" else False,
                        R02=r["overlap"] if var == "ticket" else float("nan"),
                        trained=bool(acc == acc and acc > CHANCE_ACC)))
    return pd.DataFrame(out)


def verdict(t: pd.Series, b: pd.Series | None, dense_acc: float) -> str:
    """Section-5 winning-ticket rule (single seed, so no SE test), with the baseline check."""
    if not t["trained"]:
        return "ticket failed (NaN)" if t["diverged_nan"] else "ticket failed (chance)"
    if b is None:
        return ""
    if not b["trained"]:
        return "win* (reinit at chance)" if t["acc"] >= dense_acc - 0.005 else "reinit at chance"
    adv = t["acc"] - b["acc"]
    if adv > 0 and t["acc"] >= dense_acc - 0.005:
        return "win"
    return "loss" if adv < 0 else "no win"


def tables_md(df: pd.DataFrame) -> str:
    """One markdown table per chain, ticket vs reinit at each sparsity."""
    lines = ["# Pilot tables (generated by `python -m analysis.pilot_summary`)", "",
             "S100 = eta_100 * lambda_max(step 100) / 3.8. `win*` = ticket beats a reinit that stayed at chance "
             "(inflated advantage, pilot finding P4). Chance = accuracy <= 20%. "
             "† = the mask descends from a ticket that ended at NaN or chance, which the section-5 divergence rule "
             "forbids (the pilot script only stops on NaN and does not stop the chain), so the verdict is not valid evidence.", ""]
    for (rs, cond), g in df.groupby(["run_set", "condition"], sort=False):
        a = g.iloc[0]
        dense = g[(g["round"] == 0) & (g.variant == "ticket")].iloc[0]
        lines += [f"## {SET_TITLE[rs]}: `{cond}` (eta={a.lr}, warmup={a.warmup_ep} ep)", "",
                  "| % remain | ticket acc | reinit acc | adv (pp) | ticket F1 | ticket AUC | R_0.2 | spike | S100 ticket | S100 reinit | verdict |",
                  "|---|---|---|---|---|---|---|---|---|---|---|"]
        tainted = False  # section 5 divergence rule: no mask may come from a failed (NaN/chance) ticket
        for rd, gr in g.groupby("round"):
            t = gr[gr.variant == "ticket"].iloc[0]
            b = gr[gr.variant == "reinit"].iloc[0] if (gr.variant == "reinit").any() else None
            f = lambda x, s="{:.1f}", k=100: "NaN" if x is None or x != x else s.format(k * x)
            adv = "" if b is None or t.acc != t.acc else f"{100 * (t.acc - b.acc):+.1f}"
            lines.append(f"| {t.remain_pct:.1f} | {f(t.acc)} | {'—' if b is None else f(b.acc)} | {adv} | "
                         f"{f(t.f1, '{:.3f}', 1)} | {f(t.auc, '{:.3f}', 1)} | {t.R02:.2f} | {f(t.spike, '{:.3g}', 1)} | "
                         f"{f(t.S100, '{:.2f}', 1)} | {'—' if b is None else f(b.S100, '{:.2f}', 1)} | "
                         f"{verdict(t, b, dense.acc)}{' †' if tainted else ''} |")
            tainted = tainted or not t["trained"]
        lines.append("")
    return "\n".join(lines)


def style(ax: plt.Axes) -> None:
    """Recessive axes: no top/right spines, light grid."""
    for s in ("top", "right"):
        ax.spines[s].set_visible(False)
    for s in ("left", "bottom"):
        ax.spines[s].set_color(MUTED)
    ax.tick_params(colors=DENSE, labelsize=8)
    ax.grid(True, color="#e6e5e0", lw=0.6)
    ax.set_axisbelow(True)


def fig_acc(df: pd.DataFrame, path: Path) -> None:
    """Figure A: accuracy vs % remaining, rows = run set, cols = condition; chance runs drawn as hollow x."""
    conds = ["low", "high", "high_warm"]
    fig, axes = plt.subplots(3, 3, figsize=(11, 9), sharey=True)
    for i, rs in enumerate(SETS):
        for j, cond in enumerate(conds):
            ax, g = axes[i, j], df[(df.run_set == rs) & (df.condition == cond)]
            style(ax)
            dense = g[(g["round"] == 0) & (g.variant == "ticket")].iloc[0]
            ax.axhline(100 * dense.acc if dense.trained else 10, color=DENSE, lw=1, ls="--")
            for var, col in (("ticket", TICKET), ("reinit", REINIT)):
                v = g[g.variant == var].sort_values("remain_pct")
                ok, bad = v[v.trained], v[~v.trained]
                ax.plot(ok.remain_pct, 100 * ok.acc, "-o", color=col, lw=2, ms=5, label=var)
                ax.plot(bad.remain_pct, [10] * len(bad), "x", color=col, ms=9, mew=2)
            ax.set_xscale("log")
            ax.invert_xaxis()
            ax.set_ylim(5, 95)
            a = g.iloc[0]
            ax.set_title(f"{SET_TITLE[rs]}\n{cond}: eta={a.lr}, warmup={a.warmup_ep} ep", fontsize=9, color=INK)
            if j == 0:
                ax.set_ylabel("test accuracy (%)", fontsize=9, color=DENSE)
            if i == 2:
                ax.set_xlabel("% weights remaining", fontsize=9, color=DENSE)
    axes[0, 0].legend(frameon=False, fontsize=8, loc="lower left")
    fig.text(0.5, 0.005, "dashed = dense accuracy;  x at 10% = run ended at chance or NaN "
             "(dense 'high' GPU run is itself at chance)", ha="center", fontsize=8, color=DENSE)
    fig.tight_layout(rect=(0, 0.02, 1, 1))
    fig.savefig(path, dpi=150)
    plt.close(fig)


def fig_spike(df: pd.DataFrame, path: Path) -> None:
    """Figure B: early loss spike (max loss in first 200 steps / loss at step 0) vs final accuracy."""
    fig, ax = plt.subplots(figsize=(6.5, 4.2))
    style(ax)
    v = df[df.spike.notna()].copy()
    v["acc_plot"] = (100 * v.acc).fillna(0)
    v["spike_plot"] = v.spike.clip(upper=100)  # the NaN run's spike (2.8e10) is drawn at the axis edge
    for var, col in (("ticket", TICKET), ("reinit", REINIT)):
        s = v[v.variant == var]
        ax.scatter(s.spike_plot, s.acc_plot, s=36, color=col, edgecolor="white", lw=1, label=var, zorder=3)
    for _, r in v[v.spike > 100].iterrows():
        ax.annotate(f"spike {r.spike:.1e}, NaN", (100, 0), xytext=(-8, 8), textcoords="offset points",
                    ha="right", fontsize=7, color=DENSE)
    ax.set_xscale("log")
    ax.set_xlim(0.9, 130)
    ax.axvline(8, color=MUTED, lw=1, ls=":")
    ax.set_xlabel("early loss spike (max loss, first 200 steps / loss at step 0)", fontsize=9, color=DENSE)
    ax.set_ylabel("final test accuracy (%)  [NaN plotted at 0]", fontsize=9, color=DENSE)
    ax.set_title("Spike > 8: 4/4 runs failed.  Spike ~1 failures = sparse reinits that never trained",
                 fontsize=9, color=INK)
    ax.legend(frameon=False, fontsize=8)
    fig.tight_layout()
    fig.savefig(path, dpi=150)
    plt.close(fig)


def main() -> None:
    df = load_rows()
    df.to_csv(PILOT / "pilot_summary.csv", index=False)
    (PILOT / "pilot_tables.md").write_text(tables_md(df), encoding="utf-8")
    fig_acc(df, PILOT / "fig_pilot_acc.png")
    fig_spike(df, PILOT / "fig_pilot_spike.png")
    print(f"wrote pilot_summary.csv ({len(df)} rows), pilot_tables.md, fig_pilot_acc.png, fig_pilot_spike.png")


if __name__ == "__main__":
    main()
